spring.application.name=Banking
spring.datasource.url=jdbc:postgresql://localhost:5432/Banking
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

